// <auto-generated />
namespace PLC_GenCo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fillStandardTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fillStandardTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291509505_fillStandardTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
