// <auto-generated />
namespace PLC_GenCo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class moduleModelSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moduleModelSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201806290819283_moduleModelSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
